export const API_KEY='b1cd9c8c87af8933ad0187beab32db14'
export const Basic_Url='https://api.themoviedb.org/3/movie/'
export const API_KEY_TEXT='api_key'
export const Movie_URL='popular'
export const Review_Url='/reviews'