export const API_KEY = 'b1cd9c8c87af8933ad0187beab32db14'
export const Basic_Url = 'https://api.themoviedb.org/3/movie/'
export const API_KEY_TEXT = 'api_key'
export const Movie_URL = 'popular'
export const Review_Url = '/reviews'
export const Image_URL = 'http://image.tmdb.org/t/p/w185/'
export const Search_URL = 'https://api.themoviedb.org/3/search/movie'
export const Query = '&query='